name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Publish package
        run: pnpx jsr publish